[Package]
name          = "native-dialogs"
version       = "0.1.0"
author        = "Rostyslav Dzinko (rostislav.dzinko@gmail.com)"
description   = "Implements framework-agnostic native operating system dialogs calls"
license       = "MIT"
srcDir        = "src"

[Deps]
Requires: "nim >= 0.10.0"
Requires: "oldwinapi"
Requires: "https://github.com/StefanSalewski/nim-gtk3"
Requires: "https://github.com/StefanSalewski/nim-gdk3"
Requires: "https://github.com/StefanSalewski/nim-glib"
Requires: "https://github.com/StefanSalewski/nim-gobject"
Requires: "https://github.com/StefanSalewski/nim-gio"
Requires: "https://github.com/StefanSalewski/nim-gdk_pixbuf"
Requires: "https://github.com/StefanSalewski/nim-cairo"
Requires: "https://github.com/StefanSalewski/nim-pango"
Requires: "https://github.com/StefanSalewski/nim-atk"
Requires: "https://github.com/nim-lang/oldwinapi"
